name: "Deploy to AWS"

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Install Dependencies"
        run: npm ci

      - name: "Install PM2 Globally"
        run: npm install pm2 -g

      - name: "Run Tests"
        run: npm test

      - name: "Deploy with PM2"
        run: pm2 start app.js
