name: "Deploy to AWS"

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: "Install Dependencies"
        run: npm ci

      - name: "Run Tests"
        run: npm test

      - name: "Install PM2"
        run: |
          sudo env "PATH=$PATH" npm install -g pm2

      - name: "Deploy with PM2"
        run: |
          pm2 stop my-nodejs-app || true
          pm2 start app.js --name my-nodejs-app
          pm2 save
